#!/bin/sh
#  
# beanstalkd - a simple, fast workqueue service  
#  
# chkconfig:   - 57 47  
# description: a simple, fast workqueue service  
# processname:  beanstalkd  
# config:       /etc/sysconfig/beanstalkd  
#  
### BEGIN INIT INFO  
# Provides: beanstalkd  
# Required-Start: $local_fs $network $remote_fs  
# Required-Stop: $local_fs $network $remote_fs  
# Default-Stop: 0 1 2 6  
# Short-Description: start and stop beanstalkd  
# Description: a simple, fast work-queue service  
### END INIT INFO  
# Source function library.  
. /etc/rc.d/init.d/functions

# Source networking configuration.  
. /etc/sysconfig/network  

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit
exec='/usr/local/bin/beanstalkd'
prog=$(basename $exec)

#default options, overruled by items in sysconfig
BEANSTALKD_ADDR=0.0.0.0
BEANSTALKD_PORT=11300
BEANSTALKD_USER=beanstalkd
BEANSTALKD_BINLOG_DIR=/var/log/beanstalkd/bin
BEANSTALKD_BINLOG_FSYNC_PERIOD=2000

[ -e /etc/sysconfig/beanstalkd ] && . /etc/sysconfig/beanstalkd

lockfile=/var/lock/subsys/beanstalkd

account_test() {
	local account_name=$1
	if ! egrep "^${account_name}" /etc/group &> /dev/null; then
		groupadd $account_name
	fi
	if ! egrep "^$account_name" /etc/passwd &> /dev/null; then
		useradd -r -g $account_name $account_name
	fi
}

start() {
	[ -x $exec ] || exit 5
	echo -n " Starting $prog: " 
	
	#set options
	account_test $BEANSTALKD_USER
	options="-l ${BEANSTALKD_ADDR} -p ${BEANSTALKD_PORT} -u ${BEANSTALKD_USER} "
	
	if [ "${BEANSTALKD_MAX_JOB_SIZE}" != "" ]; then
		options="${options} -z ${BEANSTALKD_MAX_JOB_SIZE}"
	fi

	if [ "${BEANSTALKD_BINLOG_DIR}" != "" ]; then
		echo " Creating binlog directory (${BEANSTALKD_BINLOG_DIR}) "
		mkdir -p ${BEANSTALKD_BINLOG_DIR} && chown ${BEANSTALKD_USER}:${BEANSTALKD_USER} ${BEANSTALKD_BINLOG_DIR}
	fi
	
	# -b binglog -f ms持久化的间隔
	options=" ${options} -b ${BEANSTALKD_BINLOG_DIR} "
	if [ ${BEANSTALKD_BINLOG_FSYNC_PERIOD} != "" ]; then
		options=" ${options} -f ${BEANSTALKD_BINLOG_FSYNC_PERIOD} "
	else
		options=" ${options} -F "
	fi

	if [ "${BEANSTALKD_BINLOG_SIZE}" != "" ]; then
		options=" ${options} -s ${BEANSTALKD_BINLOG_SIZE} "
	fi

	daemon ${exec} ${options} &
	
	retval=$?
	echo 
	[ $retval -eq 0 ] && touch $lockfile
	return $retval
}

function stop()
{
	echo -n " Stopping $prog: "

	#stop it here, often "killproc $prog"
	killproc $prog
	retval=$?
	echo 

	[ $retval -eq 0 ] && rm -f $lockfile
	set +x
	return $retval
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		stop
		start
	;;
	status)
		status $prog
	;;
	*)
		echo "Usage: ./beanstalkd.sh {start | stop | restart | status}"
		exit 1
	;;
esac
